// Normalize a string for matching: lowercase, strip punctuation, collapse spaces.
export function normalize(s: string): string {
  return s
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "") // strip accents
    .replace(/[^a-z0-9\s]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

// Map Nature Index country labels to ISO-2 codes for filtering against ROR.
// ROR uses ISO-2 codes (e.g. "US", "CN", "DE").
const COUNTRY_MAP: Record<string, string> = {
  "united states of america (usa)": "US",
  "united states of america": "US",
  "usa": "US",
  "united states": "US",
  "china": "CN",
  "germany": "DE",
  "united kingdom (uk)": "GB",
  "united kingdom": "GB",
  "uk": "GB",
  "france": "FR",
  "japan": "JP",
  "south korea": "KR",
  "korea, republic of": "KR",
  "republic of korea": "KR",
  "canada": "CA",
  "australia": "AU",
  "italy": "IT",
  "spain": "ES",
  "netherlands": "NL",
  "switzerland": "CH",
  "sweden": "SE",
  "india": "IN",
  "israel": "IL",
  "brazil": "BR",
  "russia": "RU",
  "russian federation": "RU",
  "singapore": "SG",
  "taiwan": "TW",
  "hong kong": "HK",
  "iran": "IR",
  "iran, islamic republic of": "IR",
  "poland": "PL",
  "austria": "AT",
  "belgium": "BE",
  "denmark": "DK",
  "finland": "FI",
  "norway": "NO",
  "ireland": "IE",
  "portugal": "PT",
  "greece": "GR",
  "turkey": "TR",
  "türkiye": "TR",
  "mexico": "MX",
  "argentina": "AR",
  "south africa": "ZA",
  "saudi arabia": "SA",
  "egypt": "EG",
  "pakistan": "PK",
  "new zealand": "NZ",
  "czech republic": "CZ",
  "czechia": "CZ",
  "hungary": "HU",
  "romania": "RO",
  "ukraine": "UA",
  "malaysia": "MY",
  "thailand": "TH",
  "indonesia": "ID",
  "philippines": "PH",
  "vietnam": "VN",
  "viet nam": "VN",
  "chile": "CL",
  "colombia": "CO",
  "nigeria": "NG",
  "kenya": "KE",
  "morocco": "MA",
  "algeria": "DZ",
  "tunisia": "TN",
  "united arab emirates": "AE",
  "qatar": "QA",
  "kuwait": "KW",
  "lebanon": "LB",
  "jordan": "JO",
  "iceland": "IS",
  "lithuania": "LT",
  "latvia": "LV",
  "estonia": "EE",
  "slovakia": "SK",
  "slovenia": "SI",
  "croatia": "HR",
  "serbia": "RS",
  "bulgaria": "BG",
  "cyprus": "CY",
  "luxembourg": "LU",
  "sri lanka": "LK",
  "bangladesh": "BD",
  "belarus": "BY",
  "georgia": "GE",
  "armenia": "AM",
  "azerbaijan": "AZ",
  "kazakhstan": "KZ",
  "uruguay": "UY",
  "peru": "PE",
  "venezuela": "VE",
  "ecuador": "EC",
  "cuba": "CU",
  "ghana": "GH",
  "ethiopia": "ET",
  "tanzania": "TZ",
  "uganda": "UG",
  "cameroon": "CM",
  "senegal": "SN",
  "ivory coast": "CI",
  "côte d'ivoire": "CI",
  "zimbabwe": "ZW",
  "zambia": "ZM",
  "botswana": "BW",
  "namibia": "NA",
  "oman": "OM",
  "bahrain": "BH",
  "iraq": "IQ",
  "yemen": "YE",
  "sudan": "SD",
  "syria": "SY",
  "afghanistan": "AF",
  "myanmar": "MM",
  "mongolia": "MN",
  "nepal": "NP",
  "afghanistan": "AF",
  "macao": "MO",
  "macau": "MO",
  "puerto rico": "PR",
};

export function countryToCode(country: string): string | null {
  const key = normalize(country);
  if (COUNTRY_MAP[key]) return COUNTRY_MAP[key];
  // Try matching by suffix
  for (const k of Object.keys(COUNTRY_MAP)) {
    if (key.endsWith(k) || key.includes(k)) return COUNTRY_MAP[k];
  }
  return null;
}
